version: "3.9"
services:
  ollama-mistral:
    image: ollama/ollama:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: /bin/bash
    command: /scripts/ollama-startup.sh mistral
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/mistral:/root/.ollama
      - ./scripts:/scripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-phi:
    image: ollama/ollama:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile.ollama
    entrypoint: /bin/bash
    command: /scripts/ollama-startup.sh phi
    ports:
      - "11435:11434"
    volumes:
      - ./ollama/phi:/root/.ollama
      - ./scripts:/scripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  litellm-mistral:
    build:
      context: .
      dockerfile: Dockerfile.litellm
    ports:
      - "8000:8000"
    depends_on:
      - ollama-mistral
    command: litellm --port 8000 --api_base http://ollama-mistral:11434 --model ollama/mistral
  litellm-phi:
    build:
      context: .
      dockerfile: Dockerfile.litellm
    ports:
      - "8001:8001"
    depends_on:
      - ollama-phi
    command: litellm --port 8001  --api_base http://ollama-phi:11435 --model ollama/phi
volumes:
  ollama:
